import { styled } from '@mui/material/styles';

// Only the registration modal opts into these layout and interaction styles.
export const RegistrationDialog = styled('div')({
  '--registration-error-color': '#b91c1c',
  '[data-theme="dark"] &': { '--registration-error-color': '#fca5a5' },
  '&& [role="dialog"]': { padding: '16px', overscrollBehavior: 'contain' },
  '&& .registration-form': { margin: 0 },
  '&& .registration-intro': { margin: '0 0 24px', fontSize: 13, lineHeight: 1.6, color: 'var(--text-secondary, #475569)' },
  '&& .registration-intro strong': { color: 'var(--text-h, #111827)' },
  '&& .fm-section': { marginBottom: 28 },
  '&& .fm-section:last-child': { marginBottom: 0 },
  '&& .fm-section-title': { fontSize: 12, lineHeight: 1.6, color: 'var(--nav-item-active-color, #047857)', margin: '0 0 16px', paddingBottom: 10 },
  '&& .fm-grid': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))', gap: '20px 24px', alignItems: 'start' },
  '&& .registration-patient-grid': { display: 'grid', gridTemplateColumns: 'repeat(2, minmax(0, 1fr))', gap: '20px 24px' },
  '&& .registration-patient-grid > .fm-grid, && .registration-patient-grid > .registration-conditional': { display: 'contents' },
  '&& .fm-field': { minWidth: 0, gap: 8, scrollMarginBlock: 20 },
  '&& .fm-field--error': { padding: '0 !important', border: '0 !important', background: 'transparent !important', boxShadow: 'none !important' },
  '&& .fm-label': { fontSize: 13, lineHeight: 1.5, fontWeight: 600 },
  '&& .fm-label span': { color: 'var(--registration-error-color)' },
  '&& .fm-input, && .fm-select': { minHeight: 46, height: 46, borderColor: 'var(--text-secondary, #6b7280) !important', padding: '10px 12px', fontSize: 14, lineHeight: 1.5, minWidth: 0 },
  '&& .fm-textarea': { minHeight: 96, fontSize: 14 },
  '&& .fm-input:hover:not(:disabled), && .fm-select:hover:not(:disabled)': { borderColor: 'var(--nav-item-active-color, #047857) !important' },
  '&& .fm-input:disabled, && .fm-select:disabled': { background: 'var(--bg-secondary, #f1f5f9)', color: 'var(--text-secondary, #64748b)', opacity: 1, cursor: 'not-allowed' },
  '&& .fm-field--error :is(.fm-input, .fm-select, .fm-textarea)': { borderColor: 'var(--registration-error-color) !important' },
  '&& :is(input, select, textarea, button):focus-visible': { outline: '3px solid var(--nav-item-active-color, #047857)', outlineOffset: 3, boxShadow: 'none' },
  '&& .fm-radio-group': { minHeight: 46, alignItems: 'center', paddingTop: '0 !important', gap: '8px 20px' },
  '&& .fm-radio': { minHeight: 44, padding: '0 8px', borderRadius: 6 },
  '&& .fm-radio:hover': { background: 'var(--bg-hover, #f1f5f9)' },
  '&& .fm-radio input[type="radio"]': { width: 18, height: 18, accentColor: '#047857' },
  '&& .registration-field-error': { display: 'block', fontSize: 12, lineHeight: 1.5, fontWeight: 500, color: 'var(--registration-error-color)' },
  '&& .registration-program-card': { background: 'var(--nav-item-active-bg, #f0fdf4) !important', borderColor: 'var(--input-border, #a7f3d0) !important', color: 'var(--text-h, #065f46)' },
  '&& .registration-field-hint': { fontSize: 12, lineHeight: 1.5, color: 'var(--text-secondary, #475569)' },
  '&& .registration-error': { margin: '0 0 20px', padding: '12px 16px', border: '1px solid #fecaca', borderRadius: 8, background: '#fef2f2', color: '#991b1b', fontSize: 13, lineHeight: 1.6 },
  '&& .registration-address-header': { display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 12, marginBottom: 16 },
  '&& .registration-address-header .fm-section-title': { flex: '1 1 260px', margin: 0 },
  '&& .registration-manual-toggle': { border: '1px solid var(--input-border, #cbd5e1)', borderRadius: 8, padding: '10px 14px', background: 'var(--card-bg, #fff)', color: 'var(--text-h, #334155)', fontFamily: 'inherit', fontWeight: 600, fontSize: 12, cursor: 'pointer' },
  '&& .registration-manual-toggle:hover': { background: 'var(--bg-hover, #f1f5f9)' },
  '&& .apm-address-preview': { display: 'block', marginTop: 20, padding: 16, lineHeight: 1.6, overflowWrap: 'anywhere', color: 'var(--nav-item-active-color, #065f46)' },
  '&& .apm-address-preview strong': { display: 'block', marginBottom: 4, fontSize: 12 },
  '&& button': { minHeight: 44 },
  '&& button:active:not(:disabled)': { transform: 'translateY(1px)' },
  '&& button:disabled': { cursor: 'not-allowed', opacity: 0.6 },
  '&& .fm-btn': { minHeight: 46, whiteSpace: 'normal' },
  '&& .fm-btn--submit': { background: '#047857', color: '#fff' },
  '&& .fm-btn--submit:hover:not(:disabled)': { background: '#065f46' },
  '&& .fm-btn--cancel': { color: 'var(--text-h, #334155)' },
  '&& button[aria-label="Close"]': { minWidth: 44, height: 44 },
  '@media (prefers-reduced-motion: reduce)': {
    '&& [role="dialog"], && [role="dialog"] > div': { animation: 'none' },
    '&& *': { transition: 'none' },
  },
  '@media (max-width: 599px)': {
    '&& [role="dialog"]': { padding: '8px' },
    '&& .fm-grid, && .registration-patient-grid': { gridTemplateColumns: 'minmax(0, 1fr)', gap: 18 },
    '&& .fm-input, && .fm-select, && .fm-textarea': { fontSize: 16 },
    '&& .fm-btn': { padding: '10px 12px', fontSize: 13 },
    '&& .registration-manual-toggle': { width: '100%' },
  },
});
