import { styled } from '@mui/material/styles';

export const ConsultationDialog = styled('div')({
  '--registration-error-color': '#b91c1c',
  '[data-theme="dark"] &': { '--registration-error-color': '#fca5a5' },
  '&& [role="dialog"]': { padding: '16px', overscrollBehavior: 'contain' },
  '&& .registration-form': { margin: 0 },
  '&& .registration-intro': { margin: '0 0 24px', fontSize: 13, lineHeight: 1.6, color: 'var(--text-secondary, #475569)' },
  '&& .registration-intro strong': { color: 'var(--text-h, #111827)' },
  '&& .fm-section': { marginBottom: 28 },
  '&& .fm-section:last-child': { marginBottom: 0 },
  '&& .fm-section-title': {
    fontSize: 12,
    lineHeight: 1.6,
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.6px',
    color: 'var(--nav-item-active-color, #047857)',
    margin: '0 0 16px',
    paddingBottom: 10,
    borderBottom: '1px solid var(--nav-item-active-bg, #ecfdf5)',
  },
  '&& .fm-grid': { display: 'grid', gridTemplateColumns: 'repeat(2, minmax(0, 1fr))', gap: '20px 24px', alignItems: 'start' },
  '&& .fm-grid--1': { gridTemplateColumns: 'minmax(0, 1fr)' },
  '&& .fm-grid--2': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' },
  '&& .fm-grid--full': { gridColumn: '1 / -1' },
  '&& .fm-field': { minWidth: 0, gap: 8, scrollMarginBlock: 20, display: 'flex', flexDirection: 'column' },
  '&& .fm-field--error': { padding: '0 !important', border: '0 !important', background: 'transparent !important', boxShadow: 'none !important' },
  '&& .fm-label': { fontSize: 13, lineHeight: 1.5, fontWeight: 600, color: 'var(--text-h, #374151)' },
  '&& .fm-label span': { color: 'var(--registration-error-color)', marginLeft: 2 },
  '&& .fm-input, && .fm-select': {
    minHeight: 46,
    height: 46,
    border: '1px solid var(--text-secondary, #6b7280) !important',
    borderRadius: 8,
    padding: '10px 12px',
    fontSize: 14,
    lineHeight: 1.5,
    minWidth: 0,
    boxSizing: 'border-box',
    background: 'var(--input-bg, #fff)',
    color: 'var(--input-text, #111827)',
    fontFamily: 'inherit',
    outline: 'none',
    transition: 'border-color 0.15s, box-shadow 0.15s',
  },
  '&& .fm-textarea': {
    minHeight: 96,
    fontSize: 14,
    border: '1px solid var(--text-secondary, #6b7280) !important',
    borderRadius: 8,
    padding: '10px 12px',
    background: 'var(--input-bg, #fff)',
    color: 'var(--input-text, #111827)',
    fontFamily: 'inherit',
    outline: 'none',
    resize: 'vertical',
    lineHeight: 1.5,
    boxSizing: 'border-box',
    transition: 'border-color 0.15s, box-shadow 0.15s',
  },
  '&& .fm-input:hover:not(:disabled), && .fm-select:hover:not(:disabled), && .fm-textarea:hover:not(:disabled)': {
    borderColor: '#10b981 !important',
  },
  '&& .fm-input:focus, && .fm-select:focus, && .fm-textarea:focus, && :is(input, select, textarea):focus, && :is(input, select, textarea):focus-visible': {
    outline: 'none !important',
    borderColor: '#10b981 !important',
    boxShadow: '0 0 0 4px rgba(16, 185, 129, 0.1) !important',
  },
  '&& .fm-input:disabled, && .fm-select:disabled, && .fm-textarea:disabled': {
    background: 'var(--bg-secondary, #f1f5f9)',
    color: 'var(--text-secondary, #64748b)',
    opacity: 1,
    cursor: 'not-allowed',
    borderColor: 'var(--border-color, #cbd5e1) !important',
  },
  '&& .fm-field--error :is(.fm-input, .fm-select, .fm-textarea)': {
    borderColor: 'var(--registration-error-color) !important',
  },
  '&& button:focus-visible': {
    outline: '3px solid #10b981',
    outlineOffset: 3,
    boxShadow: 'none',
  },
  '&& .fm-radio-group': {
    display: 'flex',
    minHeight: 46,
    alignItems: 'center',
    paddingTop: '0 !important',
    gap: '8px 20px',
    flexWrap: 'wrap',
  },
  '&& .fm-radio': {
    display: 'flex',
    alignItems: 'center',
    minHeight: 44,
    padding: '0 8px',
    borderRadius: 6,
    gap: 8,
    fontSize: 13,
    color: 'var(--text, #374151)',
    cursor: 'pointer',
    userSelect: 'none',
  },
  '&& .fm-radio:hover': { background: 'var(--bg-hover, #f1f5f9)' },
  '&& .fm-radio input[type="radio"]': { width: 18, height: 18, accentColor: '#047857', cursor: 'pointer' },
  '&& .registration-field-error': {
    display: 'block',
    fontSize: 12,
    lineHeight: 1.5,
    fontWeight: 500,
    color: 'var(--registration-error-color)',
    marginTop: 4,
  },
  '&& .registration-field-hint': { fontSize: 12, lineHeight: 1.5, color: 'var(--text-secondary, #475569)', marginTop: 4 },
  '&& .registration-error': {
    margin: '0 0 20px',
    padding: '12px 16px',
    border: '1px solid #fecaca',
    borderRadius: 8,
    background: '#fef2f2',
    color: '#991b1b',
    fontSize: 13,
    lineHeight: 1.6,
  },
  '&& button': { minHeight: 44 },
  '&& button:active:not(:disabled)': { transform: 'translateY(1px)' },
  '&& button:disabled': { cursor: 'not-allowed', opacity: 0.6 },
  '&& .fm-btn': {
    minHeight: 46,
    padding: '10px 24px',
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 600,
    fontFamily: 'inherit',
    cursor: 'pointer',
    border: 'none',
    transition: 'all 0.15s',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  '&& .fm-btn--submit': {
    background: '#047857',
    color: '#fff',
    boxShadow: '0 2px 8px rgba(4, 120, 87, 0.25)',
  },
  '&& .fm-btn--submit:hover:not(:disabled)': {
    background: '#065f46',
    boxShadow: '0 4px 12px rgba(4, 120, 87, 0.35)',
  },
  '&& .fm-btn--cancel': {
    background: 'var(--bg-hover, #f3f4f6)',
    color: 'var(--text-h, #334155)',
  },
  '&& .fm-btn--cancel:hover:not(:disabled)': {
    background: 'var(--bg-secondary, #e2e8f0)',
  },
  '&& button[aria-label="Close"]': { minWidth: 44, height: 44 },
  '@media (prefers-reduced-motion: reduce)': {
    '&& [role="dialog"], && [role="dialog"] > div': { animation: 'none' },
    '&& *': { transition: 'none' },
  },
  '@media (max-width: 599px)': {
    '&& [role="dialog"]': { padding: '8px' },
    '&& .fm-grid': { gridTemplateColumns: 'minmax(0, 1fr)', gap: 18 },
    '&& .fm-input, && .fm-select, && .fm-textarea': { fontSize: 16 },
    '&& .fm-btn': { padding: '10px 12px', fontSize: 13 },
  },
});
