import type { ConsultationTypesMap, TreatmentFormData } from '../types/consultation.types';

export const ANIMAL_BITE_DIAGNOSES: readonly string[] = [
  'Rabies Exposure (PEP Indicated)',
  'Suspect Rabies (Human)',
  'Wound Infection — Animal Bite',
  'Laceration / Open Wound — Bite',
  'Abrasion / Scratch — Animal',
  'Puncture Wound — Animal Bite',
  'Tetanus Prone Wound',
  'Category I Exposure (WHO)',
  'Category II Exposure (WHO)',
  'Category III Exposure (WHO)',
  'Dog Bite — Domestic',
  'Dog Bite — Stray',
  'Cat Scratch / Bite',
  'Bat Exposure',
  'Other Animal Bite',
  'Wound Abscess',
  'Cellulitis — Bite Site',
  'Allergic Reaction — Vaccine',
  'Anaphylaxis',
  'Post-Exposure Prophylaxis (PEP)',
];

export const PERTINENT_HISTORY_OPTIONS: readonly string[] = [
  'Asthma',
  'Hypertension (High blood pressure)',
  'Diabetes Mellitus',
  'Heart disease',
  'Tuberculosis (TB)',
  'Pneumonia',
  'Chronic kidney disease',
  'Liver disease',
  'Seizure/Epilepsy',
  'Allergies',
  'Previous surgery',
  'Previous hospitalization',
  'Cancer',
  'Anemia',
  'Arthritis',
  'Stroke',
  'Migraine',
  'Gastritis/Ulcer',
  'Fever',
  'Cough',
  'Difficulty breathing',
  'Chest pain',
  'Abdominal pain',
  'Headache',
  'Dizziness',
  'Vomiting',
  'Diarrhea',
  'Weakness/Fatigue',
  'Elevated blood pressure',
  'High blood sugar',
  'Allergies (Food / Drugs)',
  'Bleeding disorder',
  'Cancer / Malignancy',
  'Previous Rabies Vaccination',
  'Previous Tetanus Vaccination',
  'Immunocompromised state',
  'Pregnant / Lactating',
  'Smoker',
  'Alcohol drinker',
  'No known pertinent illness',
];

export const COMMON_CHIEF_COMPLAINTS: readonly string[] = [
  'Animal bite (Dog)',
  'Animal bite (Cat)',
  'Animal scratch',
  'Animal exposure — saliva contact',
  'Bleeding from bite wound',
  'Pain at bite site',
  'Swelling at wound area',
  'Fever post-exposure',
  'Previous bite follow-up',
  'General consultation',
  'Hypertension follow-up',
  'Diabetes follow-up',
  'Upper respiratory symptoms',
  'Migraine',
  'Gastritis/Ulcer',
  'Fever',
  'Cough',
  'Difficulty breathing',
];

export const INITIAL_CONSULTATION_TYPES: ConsultationTypesMap = {
  general: false,
  prenatal: false,
  dental_care: false,
  child_care: false,
  child_nutrition: false,
  injury: false,
  adult_immunization: false,
  family_planning: false,
  postpartum: false,
  tuberculosis: false,
  child_immunization: false,
  sick_children: false,
  firecracker_injury: false,
};

export const INITIAL_FORM_DATA: TreatmentFormData = {
  last_name: '',
  first_name: '',
  middle_name: '',
  suffix: '',
  age: '',
  address: 'Misamis Oriental',
  mode_of_transaction: 'walk-in',
  referred_from: '',
  referred_to: '',
  pertinent_history: '',
  reason_for_referral: 'For further evaluation and management.',
  actions_taken: '',
  date_of_consultation: new Date().toISOString().split('T')[0],
  consultation_time: new Date().toTimeString().slice(0, 5),
  blood_pressure: '',
  temperature: '',
  height: '',
  weight: '',
  nature_of_visit: '',
  consultation_types: INITIAL_CONSULTATION_TYPES,
  chief_complaints: '',
  diagnosis: '',
  medication_treatment: '',
  prescribed_vaccine_type: '',
  name_of_provider: '',
  laboratory_findings: '',
  performed_lab_test: '',
  name_of_attending_provider: '',
  referred_by: '',
};

export const DEFAULT_FALLBACK_VACCINES: readonly string[] = [
  'Anti-Rabies Vaccine (ARV)',
  'Tetanus Toxoid (TT)',
  'Tetanus and Diphtheria (Td)',
  'Rabies Immunoglobulin (RIG)',
  'Human Rabies Immunoglobulin (HRIG)',
  'Equine Rabies Immunoglobulin (ERIG)',
  'Amoxicillin',
  'Co-Amoxiclav (Augmentin)',
  'Metronidazole',
  'Wound Irrigation Solution',
];

export const NATURE_OF_VISIT_OPTIONS: readonly { value: 'new_consultation' | 'new_admission' | 'follow_up'; label: string }[] = [
  { value: 'new_consultation', label: 'New Consultation/Case' },
  { value: 'new_admission', label: 'New Admission' },
  { value: 'follow_up', label: 'Follow-up visit' },
];

export const CONSULTATION_TYPE_ITEMS: readonly { key: keyof ConsultationTypesMap; label: string }[] = [
  { key: 'general', label: 'General' },
  { key: 'family_planning', label: 'Family Planning' },
  { key: 'prenatal', label: 'Prenatal' },
  { key: 'postpartum', label: 'Postpartum' },
  { key: 'dental_care', label: 'Dental Care' },
  { key: 'tuberculosis', label: 'Tuberculosis' },
  { key: 'child_care', label: 'Child Care' },
  { key: 'child_immunization', label: 'Child Immunization' },
  { key: 'child_nutrition', label: 'Child Nutrition' },
  { key: 'sick_children', label: 'Sick Children' },
  { key: 'injury', label: 'Injury' },
  { key: 'firecracker_injury', label: 'Firecracker Injury' },
  { key: 'adult_immunization', label: 'Adult Immunization' },
];

export const DOCTOR_RE_EXPOSURE_OPTIONS: readonly { value: string; label: string }[] = [
  { value: '', label: 'Select Doctor Re-Exposure Plan…' },
  { value: 'two_dose_booster', label: 'Two boosters — Day 0 & Day 3 (Standard WHO/DOH Re-exposure)' },
  { value: 'single_booster', label: 'One booster — Day 0 only (Re-exposure < 3 months)' },
  { value: 'full_pep', label: 'Start full PEP — Day 0, Day 3, Day 7 (Incomplete/uncertain prior history)' },
  { value: 'continue_existing_schedule', label: 'Continue existing prescribed schedule' },
  { value: 'no_vaccine', label: 'No additional rabies vaccine indicated (Wound care / TT only)' },
];
