export interface HealthFacilityGroup {
  location: string;
  facilities: string[];
}

export const HEALTH_FACILITY_GROUPS: HealthFacilityGroup[] = [
  {
    location: 'Tagoloan (Host Municipality)',
    facilities: [
      'Tagoloan Rural Health Unit (RHU) / ABTC',
      'Barangay Poblacion Health Station (BHS)',
      'Barangay Baluarte Health Station (BHS)',
      'Barangay Natumolan Health Station (BHS)',
      'Barangay Gracia Health Station (BHS)',
      'Barangay Rosario Health Station (BHS)',
      'Barangay San Francisco Health Station (BHS)',
      'Barangay San Isidro Health Station (BHS)',
      'Barangay Sta. Ana Health Station (BHS)',
      'Barangay Tugatog Health Station (BHS)',
      'Barangay Lower Becerril Health Station (BHS)',
      'Barangay Upper Becerril Health Station (BHS)',
      'Tagoloan Polymedic General Hospital',
    ],
  },
  {
    location: 'Villanueva',
    facilities: [
      'Villanueva Rural Health Unit (RHU)',
      'Barangay Poblacion 1 Health Station (Villanueva)',
      'Barangay Poblacion 2 Health Station (Villanueva)',
      'Barangay Balacanas Health Station',
      'Barangay Dayawan Health Station',
      'Barangay Kimaya Health Station (Villanueva)',
      'Barangay San Martin Health Station',
      'Barangay Katipunan Health Station',
      'Barangay Looc Health Station',
      'Barangay Imelda Health Station',
    ],
  },
  {
    location: 'Jasaan',
    facilities: [
      'Jasaan Rural Health Unit (RHU)',
      'Barangay Upper Jasaan Health Station',
      'Barangay Lower Jasaan Health Station',
      'Barangay Bobontugan Health Station',
      'Barangay Solana Health Station',
      'Barangay Aplaya Health Station',
      'Barangay Luz Banzon Health Station',
      'Barangay Kimaya Health Station (Jasaan)',
      'Barangay Natubo Health Station',
    ],
  },
  {
    location: 'Balingasag',
    facilities: [
      'Balingasag Rural Health Unit (RHU)',
      'Misamis Oriental Provincial Hospital (MOPH) — Balingasag',
      'Barangay Poblacion Health Station (Balingasag)',
      'Barangay Baliwagan Health Station',
      'Barangay Dumarait Health Station',
      'Barangay Kauswagan Health Station (Balingasag)',
      'Barangay Waterfall Health Station',
      'Barangay Hermano Health Station',
      'Barangay Linabu Health Station',
    ],
  },
  {
    location: 'Claveria',
    facilities: [
      'Claveria Rural Health Unit (RHU)',
      'Misamis Oriental Provincial Hospital (MOPH) — Claveria',
      'Barangay Poblacion Health Station (Claveria)',
      'Barangay Patrocino Health Station',
      'Barangay Mat-i Health Station',
      'Barangay Aposkahoy Health Station',
    ],
  },
  {
    location: 'Opol',
    facilities: [
      'Opol Rural Health Unit (RHU)',
      'Barangay Poblacion Health Station (Opol)',
      'Barangay Barra Health Station',
      'Barangay Bonbon Health Station (Opol)',
      'Barangay Igpit Health Station',
      'Barangay Lower Patag Health Station',
      'Barangay Upper Patag Health Station',
      'Barangay Malanang Health Station',
    ],
  },
  {
    location: 'Cagayan de Oro City',
    facilities: [
      'Northern Mindanao Medical Center (NMMC)',
      'JR Borja General Hospital (JRBGH)',
      'City Health Office (CHO) — Cagayan de Oro',
      'Puerto Health Center (CDO)',
      'Bugo Health Center (CDO)',
      'Lapasan Health Center (CDO)',
      'Carmen Health Center (CDO)',
      'Macabalan Health Center (CDO)',
      'Kauswagan Health Center (CDO)',
      'Bulua Health Center (CDO)',
      'Macasandig Health Center (CDO)',
      'Nazareth Health Center (CDO)',
      'Gusa Health Center (CDO)',
      'Balulang Health Center (CDO)',
      'Agusan Health Center (CDO)',
      'Tablon Health Center (CDO)',
      'Cugman Health Center (CDO)',
      'Camaman-an Health Center (CDO)',
    ],
  },
  {
    location: 'Other Municipalities & Provincial Hospitals',
    facilities: [
      'Misamis Oriental Provincial Hospital (MOPH) — Talisayan',
      'Misamis Oriental Provincial Hospital (MOPH) — Manticao',
      'Misamis Oriental Provincial Hospital (MOPH) — Initao',
      'Misamis Oriental Provincial Hospital (MOPH) — Gingoog',
      'Alubijid Rural Health Unit (RHU)',
      'El Salvador City Health Office / RHU',
      'Laguindingan Rural Health Unit (RHU)',
      'Gitagum Rural Health Unit (RHU)',
      'Initao Rural Health Unit (RHU)',
      'Libertad Rural Health Unit (RHU)',
      'Sugbongcogon Rural Health Unit (RHU)',
      'Kinoguitan Rural Health Unit (RHU)',
      'Balingoan Rural Health Unit (RHU)',
      'Magsaysay Rural Health Unit (RHU)',
      'Medina Rural Health Unit (RHU)',
      'Other Barangay Health Station (Specify)',
      'Other Hospital / Medical Clinic (Specify)',
    ],
  },
];

// Helper to check if a facility name is in predefined list
export const ALL_HEALTH_FACILITIES = HEALTH_FACILITY_GROUPS.flatMap(g => g.facilities);
